name: 'Publish & Profiling'
on:
  push:
    branches:
      - 'develop'
jobs:
  router:
    name: mugen
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.PATH }}
            git pull origin develop
            make db